### ISSUE TITLE
How to enable the plugin for gitlab-CI / dockerized tests

### ISSUE THREAD

**Issue by dazza-codes** [ClearcodeHQ/pytest-postgresql#319]
```yaml
# .gitlab-ci.yml

image: python:3.6

services:
  ## https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#available-settings-for-services
  - name: kartoza/postgis:11.5-2.5
    alias: db

variables:

  # In gitlab-ci, the host connection name should be the service name or alias
  # (with all / replaced with - or _) and everything after the colon ( : ) is stripped
  POSTGRES_HOST: db  # try to use service-alias (similar to docker-compose)
  POSTGRES_PORT: 5432
  ALLOW_IP_RANGE: 0.0.0.0/0
  POSTGRES_MULTIPLE_EXTENSIONS: postgis,postgis_topology

  # Using the admin-db and user allows the CI to do anything
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASS: ''  # no passwd on gitlab-CI
  SQLALCHEMY_DATABASE_URI: "postgres://${POSTGRES_USER}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# etc etc
```

This docker provision seems to work for creating a db instance, but this plugin tries to create another one.  However, the posgresql factory can't find the `pg_ctl` to start a new instance.

```
>               raise child_exception_type(errno_num, err_msg, err_filename)
E               FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/postgresql/11/bin/pg_ctl': '/usr/lib/postgresql/11/bin/pg_ctl'
/usr/local/lib/python3.6/subprocess.py:1364: FileNotFoundError
```

It seems like this plugin needs an installation of postgresql (e.g. apt install).
