### ISSUE TITLE
migrate automerge to the shared workflow

### ISSUE THREAD

**Issue by fizyk** [ClearcodeHQ/pytest-postgresql#702]
```
jobs:
  automerge:
    uses: fizyk/actions-reuse/.github/workflows/automerge-shared.yml@v1.6.4
    secrets:
      app_id: ${{ secrets.MERGE_APP_ID }}
      private_key: ${{ secrets.MERGE_APP_PRIVATE_KEY }}
```
